[package]
name = "upack"
version = "0.1.0"
edition = "2021"

[features]
default = ["std", "infallible"]
std = ["alloc"]
alloc = []
infallible = []

[dependencies]
cfg-if = "1.0.0"

[dev-dependencies]
rand = "0.8.5"
